# Site settings
title: Scott Clark Consultancy
email: scott@stclark.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Scott Clark
email: scott@stclark.ca
facebook_username:
twitter_username: STC_Consults
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: (905)-391-2162
copyright: Scott Clark

# API settings
google_api_key:

# Build settings
markdown: kramdown